// <auto-generated />
namespace Bourse.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class V05 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(V05));
        
        string IMigrationMetadata.Id
        {
            get { return "202003230907085_V05"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
